# -*- graphql -*-
# -*- coding: utf-8 -*-
#
# michael a.g. aïvázis <michael.aivazis@para-sim.com>
# (c) 1998-2026 all rights reserved


# the root route query; houdini injects its result into +page.tsx as the {AppGreeting} prop
query AppGreeting {
	greeting
}


# end of file
